file:
  description: Delete the file or the empty folder
  fields:
    file:
      description: The file of the empty folder to be deleted
      example: '/config/snapshot.jpg'
files_in_folder:
  description: Delete files within the folder, where files are older then defined period of time
  fields:
    folder:
      description: Folder to be scanned for the files
      example: '/config/snapshots'
    time:
      description: Threshold for how old files are (in seconds). Default is 3600 seconds.
      example: 86400
    only_extensions:
      description: List of extensions that are allowed to be deleted. Cannot be combined with except_extensions.
      example: '.png'
    except_extensions:
      description: List of extensions that are not allowed to be deleted. Cannot be combined with only_extensions.
      example: '.zip'
    except_files:
      description: List of files that are not allowed to be deleted.
      example: 'important_file.zip'
    scan_subfolders:
      description: Indication if subfolders to be scanned. Default is 'false'.
      example: true
    remove_subfolders:
      description: Indication if empty subfolders to be deleted. Default is 'false'.
      example: true